---
title: "Event Driven State Machine Lab"
date: "2026-08-25"
format:
  html: default
  pdf: default
---

## State Specifications

The final project for this class will be a heart rate and temperature monitor
that will send metrics to a mobile phone using Bluetooth Low Energy (BLE).  The
device states are described in [ecg-temp-ble-lab.qmd](./ecg-temp-ble-lab.qmd).

This assigment will be the starting point to get feedback on creating a complete
and descriptive state diagram for the device.

## Generate the State Diagram

::: callout-tip
- For each state in your diagram, consider if a state would benefit from having entry/exit substates.
- Err on the side of more detail than not at this stage.
:::

1. Generate a hand-drawn (electronic or scan of paper) state diagram for the device.  Include all states, transitions, and
   events that trigger transitions.  Include any entry/exit actions for each state.
2. Electronically render your state diagram using one of the tools outlined on the [State Diagram Tools](../resources/state_diagram.qmd) page.

::: callout-tip
For UML digrams, if the diagram's layout is difficult to follow using the
automated layout, consider manually specifying relative positions and length of
arrows using the following annotation guidelines: 
[https://mermaid.ai/open-source/syntax/stateDiagram.html](https://mermaid.ai/open-source/syntax/stateDiagram.html).
:::

## Submission

Upload both renderings of your state diagram to the associated Canvas
assignment.

## Expectations

A "perfect" state diagram should not be the expectation for this assignment; constructive feedback on a thoughtful first-pass at a state diagram is the goal.  The state diagram will be used to guide the implementation of the device in future labs.